version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 12181:2181
     - 12888:2888
     - 13888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 19092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql-1:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 13306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw 
  adminer-1:
    image: adminer
    restart: always
    ports:
     - 18080:8080     
  connect:
    image: debezium/connect-jdbc:${DEBEZIUM_VERSION}
    build:
      context: ../debezium-jdbc
    ports:
     - 18083:8083
     - 15005:5005
    links:
     - kafka
     - mysql-1
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
